### ISSUE TITLE
JavaCodeFormatter error

### ISSUE THREAD

**Issue by kthoms** [sculptor/sculptor#195]
The following problem was recorded in [Eclipse Error Reporting](https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/incidents/5a251f37e4b02aaf8b2200bd):

```
Error formating code for 'E:\git\r...../ContactDTO.java'. Using original code from generator

at org.eclipse.m2e.logback.appender.EclipseLogAppender.append(EclipseLogAppender.java:49)
	
at org.eclipse.m2e.logback.appender.EclipseLogAppender.append(EclipseLogAppender.java:1)
	
at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:88)
	
at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
	
at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:280)
	
at ch.qos.logback.classic.Logger.callAppenders(Logger.java:267)
	
at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:449)
	
at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:421)
	
at ch.qos.logback.classic.Logger.error(Logger.java:554)
	
at org.sculptor.generator.formatter.JavaCodeFormatter.format(JavaCodeFormatter.java:77)
	
at org.sculptor.generator.ext.Helper._chained_fileOutput(Helper.java:2342)
	
at org.sculptor.generator.ext.Helper.fileOutput(Helper.java:111)
	
at org.sculptor.generator.template.domain.DomainObjectTmpl._chained__domainObjectBase(DomainObjectTmpl.java:2147)
	
at org.sculptor.generator.template.domain.DomainObjectTmpl._domainObjectBase(DomainObjectTmpl.java:144)
	
at org.sculptor.generator.template.domain.DomainObjectTmpl.domainObjectBase(DomainObjectTmpl.java:266)
	
at org.sculptor.generator.template.domain.DomainObjectTmpl._chained__domainObject(DomainObjectTmpl.java:1024)
	
at org.sculptor.generator.template.domain.DomainObjectTmpl._domainObject(DomainObjectTmpl.java:104)
	
at org.sculptor.generator.template.domain.DomainObjectTmpl.domainObject(DomainObjectTmpl.java:244)
	
at org.sculptor.generator.template.RootTmpl$1.apply(RootTmpl.java:148)
	
at org.sculptor.generator.template.RootTmpl$1.apply(RootTmpl.java:145)
	
at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)
	
at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)
	
at org.sculptor.generator.template.RootTmpl._chained_root(RootTmpl.java:151)
	
at org.sculptor.generator.template.RootTmplMethodDispatch.root(RootTmplMethodDispatch.java:45)
	
at org.sculptor.generator.cartridge.teleportmongodb.RootTmplExtension._chained_root(RootTmplExtension.java:106)
	
at org.sculptor.generator.cartridge.builder.RootTmplExtension._chained_root(RootTmplExtension.java:84)
	
at org.sculptor.generator.cartridge.builder.RootTmplExtension.root(RootTmplExtension.java:55)
```

**Comment by tavoda** [comment]
Can you please provide example? For now not reproducible.
